"""order paid column added

Revision ID: 7987ce5830ae
Revises: 45599e790e79
Create Date: 2022-05-01 22:31:44.128415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7987ce5830ae'
down_revision = '45599e790e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'paid')
    # ### end Alembic commands ###
