"""book.count field added

Revision ID: 8f90f66eaca4
Revises: 7987ce5830ae
Create Date: 2022-05-02 18:50:15.897812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f90f66eaca4'
down_revision = '7987ce5830ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'count')
    # ### end Alembic commands ###
