"""Book.price added, some fixes

Revision ID: bd90de543bbf
Revises: d1652e493daa
Create Date: 2022-05-01 14:48:28.244652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd90de543bbf'
down_revision = 'd1652e493daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'price')
    # ### end Alembic commands ###
